### ISSUE TITLE
Not A single otp or call came not working

### ISSUE THREAD

**Issue by gurugrover** [noob-hackers/spamx#1]
I used the tool perfectly also i used the right acess key the tool also started but not a single otp or call came tool is not working fix it asap

**Comment by Deauthxploit** [comment]
You can try this Bomber !
It doesn't have any msg limit and it also doesn't require any key 
https://github.com/anubhavanonymous/XLR8_BOMBER

**Comment by gurugrover** [comment]
> You can try this Bomber !
> It doesn't have any msg limit and it also doesn't require any key
> https://github.com/anubhavanonymous/XLR8_BOMBER

Its working well thanks for it ☺️☺️☺️
